[package]
name = "store"
description = "Store crate for below"
homepage = "https://github.com/facebookincubator/resctl"
repository = "https://github.com/danobi/resctl/"
edition = "2018"
version = "0.1.0"
authors = ['Facebook', 'Daniel Xu <dlxu@fb.com>']
license = "Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
below-thrift = "0.1"
below-common = "0.1"
below-model = "0.1"
fbthrift = "0.0.1"
anyhow = "1.0"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
humantime = "1.3"
maplit = "1.0"
memmap = "0.7"
nix = "0.19"
slog = { version = "2.5", features = ["max_level_debug"] }

[dev-dependencies]
slog-term = "2.4.2"
tempdir = "0.3"
