[package]
name = "store"
edition = "2018"
version = "0.1.0"
authors = ['Facebook', 'Daniel Xu <dlxu@fb.com>']
license = "Apache-2.0"
description = "Store crate for below"
homepage = "https://github.com/facebookincubator/resctl"
repository = "https://github.com/facebookincubator/resctl"
include = ["src/**/*.rs"]

[dependencies]
below-thrift = { path = "../if" }
common = { path = "../common" }
model = { path = "../model" }
fbthrift = { git = "https://github.com/facebook/fbthrift.git", branch = "master" }
anyhow = "1.0"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
humantime = "1.3"
maplit = "1.0"
memmap = "0.7"
nix = "0.19"
slog = { version = "2.5", features = ["max_level_debug"] }

[dev-dependencies]
slog-term = "2.4.2"
tempdir = "0.3"
