[package]
name = "render"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
common = { path = "../common" }
model = { path = "../model" }
